##########################################################
##  参数配置表 (FashionStar三自由度机械臂平行四边形结构)
##########################################################
uart: # 串口通信的配置
  port: "COM3" # 端口号
  baudrate: 115200 # 波特率(默认是 115200)
  parity: "N" # 校验方式 无 None
  stopbits: 1 # 停止位
  bytesize: 8 # 字节长度
  timeout: 0
joint: # 关节配置
  joint_num: 4 # 关节个数
  joint1: # 关节1的配置参数
    angle_min: -135.0   # 角度的最小值(单位 °)
    angle_max: 135.0    # 角度的最大值(单位 °)
    angle_default: 0.0  # 关节的默认角度(init pose里面的初始角度, 单位 °)
    servo_id: 0         # 关节的舵机ID号
  joint2: # 关节2的配置参数
    angle_min: -145.0   # 角度的最小值(单位 °)
    angle_max: 0.0      # 角度的最大值(单位 °)
    angle_default: -90.0  # 关节的默认角度(init pose里面的初始角度, 单位 °)
    servo_id: 1         # 关节的舵机ID号
  joint3: # 关节3的配置参数
    angle_min: -45.0    # 角度的最小值(单位 °)
    angle_max: 145.0    # 角度的最大值(单位 °)
    angle_default: 90.0 # 关节的默认角度(init pose里面的初始角度, 单位 °)
    servo_id: 2         # 关节的舵机ID号
  joint4: # 关节4的配置参数
    angle_min: -90.0    # 角度的最小值(单位 °)
    angle_max: 90.0     # 角度的最大值(单位 °)
    angle_default: 0.0  # 关节的默认角度(init pose里面的初始角度, 单位 °)
    servo_id: 3         # 关节的舵机ID号
  speed: # 关节转速
    min: 1.0            # 关节转速的最小值(单位 °/s)
    max: 200.0          # 关节的转速最大值(单位 °/s)
    default: 100.0      # 关节的默认转速
  joint2servo_data: # 关节标定样本数据
    theta1_n90: 91.6    # 关节1角度为-90°的时候，舵机的原始角度
    theta1_p90: -94.7   # 关节1角度为90°的时候，舵机的原始角度
    theta2_n90: -4.7    # 关节2角度为-90°的时候，舵机的原始角度
    theta2_p0: 84.1     # 关节2角度为0°的时候，舵机的原始角度
    theta3_p0: 42.8     # 关节3角度为0°的时候, 舵机的原始角度
    theta3_p90: -51.1   # 关节3角度为90°的时候, 舵机的原始角度
    theta4_n90: 90.9    # 关节4角度为-90°的时候, 舵机的原始角度
    theta4_p90: -89.9   # 关节4角度为90°的时候, 舵机的原始角度
link: # 机械臂连杆长度(单位 cm)
  link23: 8.0
  link34: 7.8
  # link45: 6.5 # 气泵: 6.5
  #             # 笔夹：8
tool: # 工具的配置
  default: 'pump' # 默认的工具
  pump: # 真空气泵
    servo_id: 254 # 气泵的舵机ID
    link45: 6.5   # 
    link56: 5.0   #
  pen:  # 画笔
    link45: 8.0
    link56: 3.0
  gripper: # 爪子
    servo_id: 4 # 爪子的舵机ID
    link45: 13.6
    link56: 0.0
motion_control: # 运动控制
  delta_t: 0.010 # 插补的时间间隔, 单位s 默认值0.010
  rad_per_step: 0.05 # 每一步走过的弧度
  